# Generated by Django 5.2.3 on 2025-08-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaclass',
            old_name='name',
            new_name='style',
        ),
    ]
