# Generated by Django 5.2.3 on 2025-08-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='name',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='YogaClass',
        ),
    ]
