# Generated by Django 5.2.3 on 2025-08-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_name_yogaclass_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaclass',
            old_name='style',
            new_name='name',
        ),
    ]
