# Generated by Django 5.2.3 on 2025-08-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('trainer', '0003_rename_whatsapp_number_trainerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.yogatype'),
        ),
    ]
