# Generated by Django 5.2.3 on 2025-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(upload_to='trainers/')),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('location', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('bio', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('yoga_types', models.ManyToManyField(to='trainer.yogatype')),
            ],
        ),
    ]
