# Generated by Django 5.2.3 on 2025-07-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainerprofile_whatsapp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='whatsapp_number',
            new_name='phone',
        ),
    ]
